#include <stdlib.h>
#include <stdio.h>

#define XWIDTH 256
#define YWIDTH 256
#define MAXVAL 65535

#if ((0x100 & 0xf) == 0x0)
#define I_M_LITTLE_ENDIAN 1
#define swap(mem) ((((mem) & (short int)0xff00) >> 8) + (((mem) & (short int)0x00ff) << 8))
#else
#define I_M_LITTLE_ENDIAN 0
#define swap(mem) (mem)
#endif

// Write a PGM image file in binary format.
void write_pgm_image(void *image, int maxval, int xsize, int ysize, const char *image_name) {
    FILE* image_file; 
    image_file = fopen(image_name, "w");
    int color_depth = 1 + (maxval > 255);
    fprintf(image_file, "P5\n# generated by pgm_util\n%d %d\n%d\n", xsize, ysize, maxval);
    fwrite(image, 1, xsize * ysize * color_depth, image_file);  
    fclose(image_file);
}

void read_pgm_image(void **image, int *maxval, int *xsize, int *ysize, const char *image_name) {
  FILE* image_file; 
  image_file = fopen(image_name, "r"); 
  *image = NULL;
  *xsize = *ysize = *maxval = 0;
  char MagicN[2];
  char *line = NULL;
  size_t n = 0;
  fscanf(image_file, "%2s%*c", MagicN );
  getline(&line, &n, image_file);
  while (line && line[0]=='#')
    getline(&line, &n, image_file);
  if (line) {
      sscanf(line, "%d%*c%d%*c%d%*c", xsize, ysize, maxval);
  } else {
      *maxval = -1;
      free(line);
      return;
  }
  free(line);
  int color_depth = 1 + (*maxval > 255);
  unsigned int size = (*xsize) * (*ysize) * color_depth;
  *image = malloc(size);
  if (*image == NULL) {
      fclose(image_file);
      *maxval = -2;
      *xsize = *ysize = 0;
      return;
  }
  if (fread(*image, 1, size, image_file) != size) {
      free(*image);
      *image = NULL;
      *maxval = -3;
      *xsize = *ysize = 0;
  }  
  fclose(image_file);
}

void swap_image(void *image, int xsize, int ysize, int maxval) {
  if (maxval > 255) {
      unsigned int size = xsize * ysize;
      for (int i = 0; i < size; i++ )
          ((unsigned short int*)image)[i] = swap(((unsigned short int*)image)[i]);
  }
}